export const socialInfo = [
    {
      facebookLink: "https://bit.ly/39IPuYf",
      twitterLink: "https://bit.ly/3CSPr8L",
      pintrestLink: "https://bit.ly/3ulG1iV",
      instagramLink: "https://www.instagram.com/p/CJ2ryqdDeyf/",
      text: "When we strive to become better than we are, everything around us becomes better too...⠀ ⠀  #better #hardwork #succes #workeverest #goals #motivation #mindset #success #inspiration #life #lifestyle #believe #quotes #happiness #positivevibes #motivationalquotes #yourself #instagram #happy #entrepreneur #positivity #inspirationalquotes #motivation #inspire #ten #entrepreneur #weareten #startup #business #hustle⠀ ⠀ ⠀ TEN App:https://buff.ly/2KXLvhN⠀ ⠀ Follow our Social Media Handles:⠀ ⠀ Join Our Community:⠀  Discord : https://buff.ly/3atYYbq⠀ ⠀ LinkedIn: https://buff.ly/3aCzEjo⠀ ⠀  Instagram: https://buff.ly/2WydfM1⠀ ⠀ FB :https://buff.ly/2Ww3JJt⠀ ⠀ Twitter: https://twitter.com/We_Are_TEN?s=09⠀ ⠀  YouTube: https://www.youtube.com/channel/UCuP4Sn3dHXrhj6DW_pm6YFg⠀ ⠀  Pinterest: https://pin.it/58K6PmL⠀ ⠀  Website: https://www.entrepreneurshipnetwork.net/",
    },
    {
      facebookLink: "https://bit.ly/39IPuYf",
      twitterLink: "https://bit.ly/3CSPr8L",
      pintrestLink: "https://bit.ly/3ulG1iV",
      instagramLink: "https://www.instagram.com/p/CJ2ryqdDeyf/",
      text: "When we strive to become better than we are, everything around us becomes better too...⠀ ⠀  #better #hardwork #succes #workeverest #goals #motivation #mindset #success #inspiration #life #lifestyle #believe #quotes #happiness #positivevibes #motivationalquotes #yourself #instagram #happy #entrepreneur #positivity #inspirationalquotes #motivation #inspire #ten #entrepreneur #weareten #startup #business #hustle⠀ ⠀ ⠀ TEN App:https://buff.ly/2KXLvhN⠀ ⠀ Follow our Social Media Handles:⠀ ⠀ Join Our Community:⠀  Discord : https://buff.ly/3atYYbq⠀ ⠀ LinkedIn: https://buff.ly/3aCzEjo⠀ ⠀  Instagram: https://buff.ly/2WydfM1⠀ ⠀ FB :https://buff.ly/2Ww3JJt⠀ ⠀ Twitter: https://twitter.com/We_Are_TEN?s=09⠀ ⠀  YouTube: https://www.youtube.com/channel/UCuP4Sn3dHXrhj6DW_pm6YFg⠀ ⠀  Pinterest: https://pin.it/58K6PmL⠀ ⠀  Website: https://www.entrepreneurshipnetwork.net/",
    },
    {
      facebookLink: "https://bit.ly/39IPuYf",
      twitterLink: "https://bit.ly/3CSPr8L",
      pintrestLink: "https://bit.ly/3ulG1iV",
      instagramLink: "https://www.instagram.com/p/CJ2ryqdDeyf/",
      text: "When we strive to become better than we are, everything around us becomes better too...⠀ ⠀  #better #hardwork #succes #workeverest #goals #motivation #mindset #success #inspiration #life #lifestyle #believe #quotes #happiness #positivevibes #motivationalquotes #yourself #instagram #happy #entrepreneur #positivity #inspirationalquotes #motivation #inspire #ten #entrepreneur #weareten #startup #business #hustle⠀ ⠀ ⠀ TEN App:https://buff.ly/2KXLvhN⠀ ⠀ Follow our Social Media Handles:⠀ ⠀ Join Our Community:⠀  Discord : https://buff.ly/3atYYbq⠀ ⠀ LinkedIn: https://buff.ly/3aCzEjo⠀ ⠀  Instagram: https://buff.ly/2WydfM1⠀ ⠀ FB :https://buff.ly/2Ww3JJt⠀ ⠀ Twitter: https://twitter.com/We_Are_TEN?s=09⠀ ⠀  YouTube: https://www.youtube.com/channel/UCuP4Sn3dHXrhj6DW_pm6YFg⠀ ⠀  Pinterest: https://pin.it/58K6PmL⠀ ⠀  Website: https://www.entrepreneurshipnetwork.net/",
    },
    {
      facebookLink: "https://bit.ly/39IPuYf",
      twitterLink: "https://bit.ly/3CSPr8L",
      pintrestLink: "https://bit.ly/3ulG1iV",
      instagramLink: "https://www.instagram.com/p/CJ2ryqdDeyf/",
      text: "When we strive to become better than we are, everything around us becomes better too...⠀ ⠀  #better #hardwork #succes #workeverest #goals #motivation #mindset #success #inspiration #life #lifestyle #believe #quotes #happiness #positivevibes #motivationalquotes #yourself #instagram #happy #entrepreneur #positivity #inspirationalquotes #motivation #inspire #ten #entrepreneur #weareten #startup #business #hustle⠀ ⠀ ⠀ TEN App:https://buff.ly/2KXLvhN⠀ ⠀ Follow our Social Media Handles:⠀ ⠀ Join Our Community:⠀  Discord : https://buff.ly/3atYYbq⠀ ⠀ LinkedIn: https://buff.ly/3aCzEjo⠀ ⠀  Instagram: https://buff.ly/2WydfM1⠀ ⠀ FB :https://buff.ly/2Ww3JJt⠀ ⠀ Twitter: https://twitter.com/We_Are_TEN?s=09⠀ ⠀  YouTube: https://www.youtube.com/channel/UCuP4Sn3dHXrhj6DW_pm6YFg⠀ ⠀  Pinterest: https://pin.it/58K6PmL⠀ ⠀  Website: https://www.entrepreneurshipnetwork.net/",
    },
    {
      facebookLink: "https://bit.ly/39IPuYf",
      twitterLink: "https://bit.ly/3CSPr8L",
      pintrestLink: "https://bit.ly/3ulG1iV",
      instagramLink: "https://www.instagram.com/p/CJ2ryqdDeyf/",
      text: "When we strive to become better than we are, everything around us becomes better too...⠀ ⠀  #better #hardwork #succes #workeverest #goals #motivation #mindset #success #inspiration #life #lifestyle #believe #quotes #happiness #positivevibes #motivationalquotes #yourself #instagram #happy #entrepreneur #positivity #inspirationalquotes #motivation #inspire #ten #entrepreneur #weareten #startup #business #hustle⠀ ⠀ ⠀ TEN App:https://buff.ly/2KXLvhN⠀ ⠀ Follow our Social Media Handles:⠀ ⠀ Join Our Community:⠀  Discord : https://buff.ly/3atYYbq⠀ ⠀ LinkedIn: https://buff.ly/3aCzEjo⠀ ⠀  Instagram: https://buff.ly/2WydfM1⠀ ⠀ FB :https://buff.ly/2Ww3JJt⠀ ⠀ Twitter: https://twitter.com/We_Are_TEN?s=09⠀ ⠀  YouTube: https://www.youtube.com/channel/UCuP4Sn3dHXrhj6DW_pm6YFg⠀ ⠀  Pinterest: https://pin.it/58K6PmL⠀ ⠀  Website: https://www.entrepreneurshipnetwork.net/",
    },
    {
      facebookLink: "https://bit.ly/39IPuYf",
      twitterLink: "https://bit.ly/3CSPr8L",
      pintrestLink: "https://bit.ly/3ulG1iV",
      instagramLink: "https://www.instagram.com/p/CJ2ryqdDeyf/",
      text: "When we strive to become better than we are, everything around us becomes better too...⠀ ⠀  #better #hardwork #succes #workeverest #goals #motivation #mindset #success #inspiration #life #lifestyle #believe #quotes #happiness #positivevibes #motivationalquotes #yourself #instagram #happy #entrepreneur #positivity #inspirationalquotes #motivation #inspire #ten #entrepreneur #weareten #startup #business #hustle⠀ ⠀ ⠀ TEN App:https://buff.ly/2KXLvhN⠀ ⠀ Follow our Social Media Handles:⠀ ⠀ Join Our Community:⠀  Discord : https://buff.ly/3atYYbq⠀ ⠀ LinkedIn: https://buff.ly/3aCzEjo⠀ ⠀  Instagram: https://buff.ly/2WydfM1⠀ ⠀ FB :https://buff.ly/2Ww3JJt⠀ ⠀ Twitter: https://twitter.com/We_Are_TEN?s=09⠀ ⠀  YouTube: https://www.youtube.com/channel/UCuP4Sn3dHXrhj6DW_pm6YFg⠀ ⠀  Pinterest: https://pin.it/58K6PmL⠀ ⠀  Website: https://www.entrepreneurshipnetwork.net/",
    },
    {
      facebookLink: "https://bit.ly/39IPuYf",
      twitterLink: "https://bit.ly/3CSPr8L",
      pintrestLink: "https://bit.ly/3ulG1iV",
      instagramLink: "https://www.instagram.com/p/CJ2ryqdDeyf/",
      text: "When we strive to become better than we are, everything around us becomes better too...⠀ ⠀  #better #hardwork #succes #workeverest #goals #motivation #mindset #success #inspiration #life #lifestyle #believe #quotes #happiness #positivevibes #motivationalquotes #yourself #instagram #happy #entrepreneur #positivity #inspirationalquotes #motivation #inspire #ten #entrepreneur #weareten #startup #business #hustle⠀ ⠀ ⠀ TEN App:https://buff.ly/2KXLvhN⠀ ⠀ Follow our Social Media Handles:⠀ ⠀ Join Our Community:⠀  Discord : https://buff.ly/3atYYbq⠀ ⠀ LinkedIn: https://buff.ly/3aCzEjo⠀ ⠀  Instagram: https://buff.ly/2WydfM1⠀ ⠀ FB :https://buff.ly/2Ww3JJt⠀ ⠀ Twitter: https://twitter.com/We_Are_TEN?s=09⠀ ⠀  YouTube: https://www.youtube.com/channel/UCuP4Sn3dHXrhj6DW_pm6YFg⠀ ⠀  Pinterest: https://pin.it/58K6PmL⠀ ⠀  Website: https://www.entrepreneurshipnetwork.net/",
    },
    {
      facebookLink: "https://bit.ly/39IPuYf",
      twitterLink: "https://bit.ly/3CSPr8L",
      pintrestLink: "https://bit.ly/3ulG1iV",
      instagramLink: "https://www.instagram.com/p/CJ2ryqdDeyf/",
      text: "When we strive to become better than we are, everything around us becomes better too...⠀ ⠀ #better #hardwork #succes #workeverest #goals #motivation #mindset #success #inspiration #life #lifestyle #believe #quotes #happiness #positivevibes #motivationalquotes #yourself #instagram #happy #entrepreneur #positivity #inspirationalquotes #motivation #inspire #ten #entrepreneur #weareten #startup #business #hustle⠀ ⠀ ⠀ TEN App:https://buff.ly/2KXLvhN⠀ ⠀ Follow our Social Media Handles:⠀ ⠀ Join Our Community:⠀  Discord : https://buff.ly/3atYYbq⠀ ⠀ LinkedIn: https://buff.ly/3aCzEjo⠀ ⠀  Instagram: https://buff.ly/2WydfM1⠀ ⠀ FB :https://buff.ly/2Ww3JJt⠀ ⠀ Twitter: https://twitter.com/We_Are_TEN?s=09⠀ ⠀  YouTube: https://www.youtube.com/channel/UCuP4Sn3dHXrhj6DW_pm6YFg⠀ ⠀  Pinterest:https://pin.it/58K6PmL⠀ ⠀ Website: https://www.entrepreneurshipnetwork.net/",
    },
  ];